### ISSUE TITLE
Fails to provision containers on machines where the active user doesn't have a uid of 1000.

### ISSUE THREAD

**Issue by ChrisTimperley** [squaresLab/BugZoo#131]
Prior to provisioning a Docker container for a given bug, BugZoo generates a environmental variables file as a named temporary file on the host machine. That file is then mounted at `./environment` inside the provisioned container. At launch, the container calls `source "./environment" to load the values of environmental variables.

Since Docker retains ownership information during volume sharing, `./environment` will have the same owner UID as the UID of the user on the host machine. All of the ManyBugs containers run with a `docker` user with `uid=1000`. On most Ubuntu installations, the "main user" has a uid of 1000, and so no error is observed. For multi-user installations (e.g., servers), the active user may not have a uid of 1000, and so the `./environment` file will have a different UID to the UID of the `docker` user inside the container. The mismatch between the UID of the `./environment` file and the `docker` user prevents the `./environment` file from being source, which causes the provisioning process to fail.

An adequate solution would be to change ownership of the `./environment` file using `chown` during the provisioning process.

**Comment by ChrisTimperley** [comment]
@joerenzullo this may affect you on your compute cluster.

**Comment by joerenzullo** [comment]
Thanks for the heads-up!

ASU are provisioning a private VM for me to use (I've asked for 64 cores), so I'll be sure to pay attention to this when they get that up and running for me.

It wasn't possible to use docker with the existing compute facilities because their work manager doesn't play nice w/ Docker (think they are using an older version of SLURM).

**Comment by ChrisTimperley** [comment]
Changing ownership of the file at the beginning of the provisioning process manages to avoid _this_ bug, but it also introduces another: when we try to delete the temporary file that we mounted inside the container, we no longer have permission to do so (since its UID matches the UID of the `docker` user inside the bug container).

To solve this issue, the temporary file should be mounted to `/.environment.host` (in a read-only mode), before being copied to `/.environment`.
