### ISSUE TITLE
"bugzoo bug build" fails to resolve url repairbenchmarks.cs.umass.edu (ManyBugs)

### ISSUE THREAD

**Issue by sgalla** [squaresLab/BugZoo#214]
Attempting "bugzoo bug build" on any of the manybugs benchmark bugs results in a failure with the following error message:

**wget: unable to resolve host address 'repairbenchmarks.cs.umass.edu'
...
bugzoo.core.errors.ImageBuildFailed: squaresLab/<bug-name>**

I did notice that the bug name in the error message is slightly different than the bug name according to "bugzoo bug list". I'm not sure if this has anything to do with the error, but for example, when trying to build manybugs:lighttpd:2661-2662, the bug name in the error message is manybugs:lighttpd-2661-2662 (the second colon is replaced with a hyphen).

**Comment by ChrisTimperley** [comment]
Thanks for reporting this.

The difference between the two names is expected.

Unfortunately, for the time being, the ManyBugs BugZoo images rely on the original ManyBugs archives that are hosted on `repairbenchmarks.cs.umass.edu`. It's possible that the server went down or your machine was unable to see it. Could you perhaps dump the complete output from BugZoo? Also, could you let me know what version of BugZoo you're using?

**Comment by sgalla** [comment]
I've been able to both ping and do a manual wget on the url and can connect successfully from my machine. I'm using the most recent BugZoo (2.1.6). Below is the BugZoo output from "bugzoo bug build manybugs:lighttpd:2661-2662":

building bug: manybugs:lighttpd:2661-2662
Building image: squareslab/manybugs:lighttpd-2661-2662
Step 1/14 : FROM squareslab/manybugs:lighttpd

 ---> 0b2d133be66b
Step 2/14 : ARG bug_commit

 ---> Using cache
 ---> 52c119aaaa26
Step 3/14 : ARG fix_commit

 ---> Using cache
 ---> 141339f16fc6
Step 4/14 : ENV BUG_COMMIT ${bug_commit}

 ---> Using cache
 ---> 3a91d5b12907
Step 5/14 : ENV FIX_COMMIT ${fix_commit}

 ---> Using cache
 ---> b30d2e7a0bf2
Step 6/14 : ENV SCENARIO_NAME lighttpd-bug-${BUG_COMMIT}-${FIX_COMMIT}

 ---> Using cache
 ---> 85f4a760e440
Step 7/14 : ENV OLD_LOCATION /root/mountpoint-genprog/genprog-many-bugs/${SCENARIO_NAME}

 ---> Using cache
 ---> 264aef61e6fa
Step 8/14 : RUN cd /experiment &&     wget  -nv http://repairbenchmarks.cs.umass.edu/ManyBugs/scenarios/${SCENARIO_NAME}.tar.gz           -O scenario.tar.gz &&     tar -xf scenario.tar.gz &&     mv ${SCENARIO_NAME} scenario &&     rm scenario.tar.gz &&     cd scenario &&     rm -rf  coverage*             configuration-oracle             local-root             limit*             *.cache             *.debug.*             sanity             compile.pl             *~             test             reconfigure             preprocessed             fixed-program.txt &&     mv bug-failures bug-info &&     mv bugged-program.txt manifest.txt &&     mv *.lines bug-info &&     mv fix-failures bug-info &&     mv lighttpd src &&     cd ../ &&     mv scenario/* /experiment &&     rm -rf scenario &&     cd /experiment &&     rm -rf tests &&     cd /experiment/src &&       make distclean &&       svn upgrade &&       svn revert $(cat /experiment/manifest.txt) &&     sudo chown -R docker /experiment

 ---> Running in fae1f9d21609
wget: unable to resolve host address 'repairbenchmarks.cs.umass.edu'

Traceback (most recent call last):
  File "/home/scgalla1/.local/bin/bugzoo", line 11, in <module>
    sys.exit(main())
  File "/home/scgalla1/.local/lib/python3.5/site-packages/bugzoo/cli/__init__.py", line 532, in main
    args.func(args)
  File "/home/scgalla1/.local/lib/python3.5/site-packages/bugzoo/cli/__init__.py", line 487, in <lambda>
    cmd.set_defaults(func=lambda args: build_bug(rbox, args.bug, args.force))
  File "/home/scgalla1/.local/lib/python3.5/site-packages/bugzoo/cli/__init__.py", line 101, in build_bug
    rbox.bugs.build(bug, force=force)
  File "/home/scgalla1/.local/lib/python3.5/site-packages/bugzoo/mgr/bug.py", line 83, in build
    quiet=quiet)
  File "/home/scgalla1/.local/lib/python3.5/site-packages/bugzoo/mgr/build.py", line 124, in build
    raise ImageBuildFailed(name, log)
bugzoo.core.errors.ImageBuildFailed: squareslab/manybugs:lighttpd-2661-2662

**Comment by ChrisTimperley** [comment]
That's strange. I just redownloaded the ManyBugs repo from scratch and successfully built that particular bug. Could you also share the output of `docker info`?

**Comment by sgalla** [comment]
Hmmm... my docker info output:

Containers: 19
 Running: 0
 Paused: 0
 Stopped: 19
Images: 97
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-124-generic
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 24
Total Memory: 125.9GiB
Name: minke
ID: UVBR:COZX:LQSO:JKKF:TQZC:E6HW:SM4T:JFTX:AU5T:S7UA:AK3C:34JD
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by ChrisTimperley** [comment]
Just as a sanity check, can you try to run the command below:

```
$ docker run --rm -it busybox
/ # wget http://repairbenchmarks.cs.umass.edu/ManyBugs/scenarios/lighttpd-bug-2661-2662.tar.gz
```

**Comment by sgalla** [comment]
When I run that wget it hangs for a long time and eventually outputs:

wget: bad address 'repairbenchmarks.cs.umass.edu'

**Comment by sgalla** [comment]
Also, a ping from busybox on 8.8.8.8 fails...

**Comment by ChrisTimperley** [comment]
Hmm, it looks like there's some kind of network/firewall issue with your Docker installation.

**Comment by sgalla** [comment]
You're right... we restarted the docker service and we are now able to make network connections from within containers. However, when trying to build that bug, we're now seeing another error that causes the build to fail. See bugzoo output below.

building bug: manybugs:lighttpd:2661-2662
Building image: squareslab/manybugs:lighttpd-2661-2662
Step 1/14 : FROM squareslab/manybugs:lighttpd

 ---> 0b2d133be66b
Step 2/14 : ARG bug_commit

 ---> Using cache
 ---> 52c119aaaa26
Step 3/14 : ARG fix_commit

 ---> Using cache
 ---> 141339f16fc6
Step 4/14 : ENV BUG_COMMIT ${bug_commit}

 ---> Using cache
 ---> 3a91d5b12907
Step 5/14 : ENV FIX_COMMIT ${fix_commit}

 ---> Using cache
 ---> b30d2e7a0bf2
Step 6/14 : ENV SCENARIO_NAME lighttpd-bug-${BUG_COMMIT}-${FIX_COMMIT}

 ---> Using cache
 ---> 85f4a760e440
Step 7/14 : ENV OLD_LOCATION /root/mountpoint-genprog/genprog-many-bugs/${SCENARIO_NAME}

 ---> Using cache
 ---> 264aef61e6fa
Step 8/14 : RUN cd /experiment &&     wget  -nv http://repairbenchmarks.cs.umass.edu/ManyBugs/scenarios/${SCENARIO_NAME}.tar.gz           -O scenario.tar.gz &&     tar -xf scenario.tar.gz &&     mv ${SCENARIO_NAME} scenario &&     rm scenario.tar.gz &&     cd scenario &&     rm -rf  coverage*             configuration-oracle             local-root             limit*             *.cache             *.debug.*             sanity             compile.pl             *~             test             reconfigure             preprocessed             fixed-program.txt &&     mv bug-failures bug-info &&     mv bugged-program.txt manifest.txt &&     mv *.lines bug-info &&     mv fix-failures bug-info &&     mv lighttpd src &&     cd ../ &&     mv scenario/* /experiment &&     rm -rf scenario &&     cd /experiment &&     rm -rf tests &&     cd /experiment/src &&       make distclean &&       svn upgrade &&       svn revert $(cat /experiment/manifest.txt) &&     sudo chown -R docker /experiment

 ---> Using cache
 ---> fa8a3dd00557
Step 9/14 : RUN sed -i "s#${OLD_LOCATION}#/experiment#g" test.sh &&     sed -i "s#cd gmp#cd src#g" test.sh &&     sed -i "s#/experiment/limit#timeout 5#g" test.sh &&     sed -i "s#/usr/bin/perl#perl#g" test.sh &&     sed -i 's#lt-\.\*#lt-\.\* \&\> /dev/null#g' test.sh &&     sed -i 's#cd lighttpd/tests#cd src/tests#g' test.sh &&     sed -i 's#cd src/tests#pushd /experiment/src/tests#g' test.sh &&     sed -i 's#cd ../../#popd#g' test.sh

 ---> Using cache
 ---> 3693151ce8b9
Step 10/14 : RUN sed -i 's#image.JPG#image.jpg#g' src/tests/core-request.t

 ---> Using cache
 ---> 2ab0d27d1dc9
Step 11/14 : RUN cd src/tests/tmp/lighttpd/servers/www.example.org/pages &&     rm symlinked index.xhtml &&     ln -s expire symlinked &&     ln -s index.html index.xhtml

 ---> Using cache
 ---> 97ba6504ea7f
Step 12/14 : ADD mod-cgi.t /experiment/src/tests/mod-cgi.t

 ---> Using cache
 ---> 9cbbb8af7d29
Step 13/14 : RUN ./preprocess --cfg "--with-ldap --with-bzip2 --with-openssl --with-gdbm --with-memcache --with-webdav-props --with-webdav-locks" &&     cd src &&     make

 ---> Running in d6b6d6f2b033
usage: preprocess [-h] [--m32] [--obj] [--base]
preprocess: error: unrecognized arguments: --cfg --with-ldap --with-bzip2 --with-openssl --with-gdbm --with-memcache --with-webdav-props --with-webdav-locks

Traceback (most recent call last):
  File "/usr/local/bin/bugzoo", line 9, in <module>
    load_entry_point('bugzoo==2.1.6', 'console_scripts', 'bugzoo')()
  File "/usr/local/lib/python3.5/dist-packages/bugzoo/cli/__init__.py", line 539, in main
    args.func(args)
  File "/usr/local/lib/python3.5/dist-packages/bugzoo/cli/__init__.py", line 488, in <lambda>
    cmd.set_defaults(func=lambda args: build_bug(rbox, args.bug, args.force))
  File "/usr/local/lib/python3.5/dist-packages/bugzoo/cli/__init__.py", line 102, in build_bug
    rbox.bugs.build(bug, force=force)
  File "/usr/local/lib/python3.5/dist-packages/bugzoo/mgr/bug.py", line 83, in build
    quiet=quiet)
  File "/usr/local/lib/python3.5/dist-packages/bugzoo/mgr/build.py", line 124, in build
    raise ImageBuildFailed(name, log)
bugzoo.exceptions.ImageBuildFailed: failed to build Docker image: squareslab/manybugs:lighttpd-2661-2662

**Comment by ChrisTimperley** [comment]
What's the output of `bugzoo source list`?

**Comment by ChrisTimperley** [comment]
Also, can you try to build with `bugzoo bug build --force`? It may be building on top of an old version of the base image.

**Comment by joerenzullo** [comment]
bugzoo bug build --force seems to have fixed the problem!

For completeness, on `bugzoo source list` I get a ton of debug messages, ending with:
INFO:bugzoo.mgr.source:2018-05-18 15:57:55,831: "coverage.files-to-instrument" for manybugs:python:69368-69372: []
INFO:bugzoo.mgr.source:2018-05-18 15:57:55,832: "coverage.files-to-instrument" for manybugs:python:69709-69710: []
INFO:bugzoo.mgr.source:2018-05-18 15:57:55,833: "coverage.files-to-instrument" for manybugs:python:70120-70124: []
INFO:bugzoo.mgr.source:2018-05-18 15:57:55,834: "coverage.files-to-instrument" for manybugs:python:69470-69474: []
INFO:bugzoo.mgr.source:2018-05-18 15:57:55,835: "coverage.files-to-instrument" for manybugs:python:69934-69935: []
INFO:bugzoo.mgr.source:2018-05-18 15:57:55,836: "coverage.files-to-instrument" for manybugs:python:69740-69743: []
INFO:bugzoo.mgr.source:2018-05-18 15:57:55,837: "coverage.files-to-instrument" for manybugs:python:69609-69616: []
INFO:bugzoo.mgr.source:2018-05-18 15:57:55,840: loaded source: manybugs
INFO:bugzoo.mgr.source:2018-05-18 15:57:55,840: loading source genprog at /home/jvrenzul/.bugzoo/sources/github_com_squaresLab_genprog-code
INFO:bugzoo.mgr.source:2018-05-18 15:57:55,852: loaded source: genprog
INFO:bugzoo.mgr.source:2018-05-18 15:57:55,852: refreshed sources

Source    Type    URL                                         Location                                                           Version
--------  ------  ------------------------------------------  -----------------------------------------------------------------  ---------
genprog   Remote  https://github.com/squaresLab/genprog-code  /home/jvrenzul/.bugzoo/sources/github_com_squaresLab_genprog-code  b4de21d7
manybugs  Remote  https://github.com/squaresLab/ManyBugs      /home/jvrenzul/.bugzoo/sources/github_com_squaresLab_ManyBugs      ad83bd9a

**Comment by ChrisTimperley** [comment]
This problem wouldn't have occurred if BugZoo implemented #187. Any thoughts on #187, @joerenzullo and @sgalla?

**Comment by ChrisTimperley** [comment]
Apologies for the debug messages. They'll disappear (to a file on disk) in the next release.

**Comment by joerenzullo** [comment]
I think absolutely implement #187 . If I already have a working version of a bug, I'm very unlikely to invoke `bugzoo bug build`. Conversely, if I am invoking it, I'd much rather wait a small amount of extra time to rebuild from scratch to ensure it works properly (or is more likely to work properly) than have it be fast and less likely.

Thanks for your help!

**Comment by ChrisTimperley** [comment]
Okay, great; I'll schedule #187 for the next release.
