### ISSUE TITLE
No obvious way to import repairbox.manager from within examples/manybugs.py 

### ISSUE THREAD

**Issue by HalleyYoung** [squaresLab/BugZoo#234]
After some searching, I was unable to find the location of a python module "repairbox" which has submodule "manager" (I found the python executable repairbox in https://github.com/afsafzal/RepairBox, but not a folder or python module containing any submodules).  Where can I find this package to import?

Many thanks!

**Comment by ChrisTimperley** [comment]
You should be able to find the information you need here: https://squareslab.github.io/BugZoo/index.html

Some of the examples in the `examples/` directory are out of date, but the documentation should contain up-to-date examples and API/CLI information.

If you have any more problems, feel free to drop a message on the discussion board: https://gitq.com/squaresLab/BugZoo
