### ISSUE TITLE
Can we add the GenProg Debug image to squareslab/genprog for use with Bugzoo?

### ISSUE THREAD

**Issue by pdreiter** [squaresLab/BugZoo#334]
with the `--with genprog` command line to bugzoo, the `squareslab/genprog` is added to the bugzoo container, but I have a need to use the debug version of genprog in bugzoo containers.  
In order to do this, need:
1) ocamldebug installed (opam, ocaml)
2) need to build debug version of genprog, from git base dir of genprog clone: 
- `cd src`
- `make repair.byte`
- `cp repair.byte /opt/genprog/bin/genprog.byte`

**Comment by ChrisTimperley** [comment]
Have you tried to create that GenProg image yourself by modifying the `Dockerfile` in the repo?
https://github.com/squaresLab/genprog-code/blob/master/Dockerfile

**Comment by pdreiter** [comment]
Yep! That’s exactly what I did for myself yesterday, but the hard way (from scratch) since I did not see the dockerfile.

**Comment by ChrisTimperley** [comment]
Moved issue to https://github.com/squaresLab/genprog-code/pull/27
