### ISSUE TITLE
ImageMagick fails to compile

### ISSUE THREAD

**Issue by ChrisTimperley** [squaresLab/BugZoo#38]
When attempting to make, the following errors are displayed:

```
magick/blob.c:2679:13: error: ‘FILE {aka struct _IO_FILE}’ has no member named ‘have’
           c=gzgetc(image->blob->file);
             ^
magick/blob.c:2679:13: error: ‘FILE {aka struct _IO_FILE}’ has no member named ‘have’
           c=gzgetc(image->blob->file);
             ^
magick/blob.c:2679:13: error: ‘FILE {aka struct _IO_FILE}’ has no member named ‘pos’
           c=gzgetc(image->blob->file);
             ^
magick/blob.c:2679:13: error: ‘FILE {aka struct _IO_FILE}’ has no member named ‘next’
           c=gzgetc(image->blob->file);
```

**Comment by ChrisTimperley** [comment]
Similar errors:
http://forum.simutrans.com/index.php?topic=9575.0;wap
http://ubuntuforums.org/archive/index.php/t-79490.html

**Comment by ChrisTimperley** [comment]
It looks like this may be due to an incompatibility with newer versions of zlib: https://github.com/rieck/sally/issues/2

**Comment by ChrisTimperley** [comment]
https://github.com/divx118/kboot/blob/master/package/imagemagick/imagemagick-zlib-fix.patch

**Comment by ChrisTimperley** [comment]
No longer relevant.

**Comment by lei-houjyu** [comment]
> https://github.com/divx118/kboot/blob/master/package/imagemagick/imagemagick-zlib-fix.patch

This patch works for me. Thanks!
