### ISSUE TITLE
Path problems lead to failure to compile for various php scenarios.

### ISSUE THREAD

**Issue by clegoues** [squaresLab/BugZoo#49]
So far, CLG has noticed this in:

php-bug-2012-03-12-438a30f1e7-7337a901b7
php-bug-2012-03-08-0169020e49-cdc512afb3

And she will update when she finds more.

**Comment by ChrisTimperley** [comment]
Rebuilt src archives for both and added additional instruction to prepare.sh to regenerate configure

**Comment by clegoues** [comment]
(Updated with a third possible problem scenario)

**Comment by ChrisTimperley** [comment]
Rebuilt all PHP scenarios from scratch (within Dockerfile).
