### ISSUE TITLE
Symbolic link in gmp-bug-14166-14167 prevents configure from completing

### ISSUE THREAD

**Issue by ChrisTimperley** [squaresLab/BugZoo#51]
`src/ltmain.sh` points to `/usr/share/libtool/config/ltmain.sh`, but this file no longer exists on newer versions of libtool (the equivalent file can be found at `/usr/share/libtool/build-aux/ltmain.sh`).

**Comment by ChrisTimperley** [comment]
@eduardodx I don't suppose you had this problem as well?

**Comment by eduardodx** [comment]
@ChrisTimperley As I'm using the chroot (inside docker), I still have the old libtool. But I stepped into this problem while working with the latest Fedora/Ubuntu.

**Comment by ChrisTimperley** [comment]
Addressed in https://github.com/squaresLab/RepairBox/pull/67
