### ISSUE TITLE
scenarios missing from repository

### ISSUE THREAD

**Issue by manishmotwani3** [squaresLab/BugZoo#54]
Following scenarios are missing from the repository.

- libtiff-bug-2007-07-08-bd2f947-ccc10c7 / ibtiff-bug-cb57a69f-740a6187
- libtiff-bug-2007-07-08-c766cb7-0cc95fb / libtiff-bug-b675f33d-5d9d496d
- libtiff-bug-2007-07-13-09e8220-f2d989d / libtiff-bug-031c6a9b-14f51686 
- libtiff-bug-2008-04-15-2e8b2f1-0d27dc0 / libtiff-bug-806c4c9-366216b
- libtiff-bug-2008-09-05-d59e7df-5f42dba / libtiff-bug-34285ec-b0492c2

Also, bug-info folder is missing from many of the existing libtiff scenarios.

**Comment by ChrisTimperley** [comment]
Hey Manish, I'll take a look at these this evening. I need to realign the libtiff scenarios and to ensure that they match up with their newer versions provided in the ManyBugs dataset.

**Comment by ChrisTimperley** [comment]
Just added all of the ManyBugs Libtiff scenarios, although they're failing in an unexpected way. All missing folders should now be present.

**Comment by ChrisTimperley** [comment]
Rebuilt all Libtiff, Python, PHP and GZip scenarios from source.
