### ISSUE TITLE
Simplify build process to allow construction of a single manybugs scenario.

### ISSUE THREAD

**Issue by clegoues** [squaresLab/BugZoo#56]
Chris seems to think that "Rake" is the answer here and I believe him.

**Comment by ChrisTimperley** [comment]
Implemented new custom build system. All interaction with RepairBox is carried out via the "repairbox" client executable. This executable is responsible for building, downloading, uploading, and launching bug scenarios. I'm also adding a few simple functions for querying bug scenarios (for now, it's just limited to listing all available bug scenarios).

To build a particular bug scenario, one may use the following command:

```
$ repairbox build manybugs:php:php-xyz-zyx
```

To build all of the bug scenarios belonging to a particular program:

```
$ repairbox build manybugs:php
```

To build all the bug scenarios belonging to a particular dataset:

```
$ repairbox build manybugs
```

To build ALL the bug scenarios

```
$ repairbox build all
```

To add a new bug scenario, contributors just need to drop in a ".bug.yaml" file :-)

**Comment by ChrisTimperley** [comment]
Finished implementing new build system.

Users can also download pre-built boxes from the command line using the following command:

```
$ repairbox download manybugs:python:blah-blah
```
