### ISSUE TITLE
repairbox "download" command doesn't work as expected

### ISSUE THREAD

**Issue by manishmotwani3** [squaresLab/BugZoo#61]
The command  repairbox download bug manybugs:libtiff:2005-12-14-6746b87-0d3d51d 
(same as mentioned in documentation) 

throws error 
usage: repairbox [-h] [--version]
                 {build,upload,download,install,uninstall,list,execute,launch}
                 ...
repairbox: error: unrecognized arguments: manybugs:libtiff:2005-12-14-6746b87-0d3d51d

**Comment by ChrisTimperley** [comment]
New CLI addresses this issue.
