### ISSUE TITLE
compilation error for php scenarios: php-bug-2011-11-19-51a4ae6576-bc810a443d and php-bug-2011-10-15-0a1cc5f01c-05c5c8958e

### ISSUE THREAD

**Issue by manishmotwani3** [squaresLab/BugZoo#62]
compiling scenarios throws error: 

```
/bin/bash: line 1:  2324 Segmentation fault      (core dumped) ` if test -x "/experiment/src/sapi/cli/php"; then /experiment/src/build/shtool echo -n -- "/experiment/src/sapi/cli/php -n"; if test "x" != "x"; then /experiment/src/build/shtool echo -n -- " -d extension_dir=/experiment/src/modules"; for i in bz2 zlib phar; do if test -f "/experiment/src/modules/$i.la"; then . /experiment/src/modules/$i.la; /experiment/src/build/shtool echo -n -- " -d extension=$dlname"; fi; done; fi; else /experiment/src/build/shtool echo -n -- "/experiment/src/sapi/cli/php"; fi;` -d 'open_basedir=' -d 'output_buffering=0' -d 'memory_limit=-1' -d phar.readonly=0 -d 'safe_mode=0' /experiment/src/ext/phar/build_precommand.php > ext/phar/phar.php
make: *** [ext/phar/phar.php] Error 139
```

and running generated executable (src/sapi/cli/php) for anything (e.g. ./php -version) throws:

```
Segmentation fault (core dumped)
```

**Comment by ChrisTimperley** [comment]
Hi Manish, it sounds like PHAR should be disabled during the `./configure` stage for these two particular bug scenarios. I'll update the bug manifests accordingly, but in the meantime, just go ahead and configure with an additional `--disable-phar` flag.

**Comment by manishmotwani3** [comment]
I tried doing that and project seems to successfully compile however running the generated executable 
( src/sapi/cli/php) still throws segmentation fault. You can reproduce this by running ./php -v

**Comment by ChrisTimperley** [comment]
https://bugs.php.net/bug.php?id=51216

**Comment by ChrisTimperley** [comment]
Various PHP compilation issues have been addressed.
